// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3ayAYoO3mO9lS7H-he_EzPZPLG9prFo',
    appId: '1:819053432548:web:8edf3e834dc214674a26f1',
    messagingSenderId: '819053432548',
    projectId: 'flutter-instagram-f27bd',
    authDomain: 'flutter-instagram-f27bd.firebaseapp.com',
    storageBucket: 'flutter-instagram-f27bd.appspot.com',
    measurementId: 'G-5C6Z7H3BST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0cXONVyVIFrcAXujoWnUcQnkloiFXgGM',
    appId: '1:819053432548:android:1bc2b51296248a674a26f1',
    messagingSenderId: '819053432548',
    projectId: 'flutter-instagram-f27bd',
    storageBucket: 'flutter-instagram-f27bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PudpcejMzoa9tpBolWxCLDfckkMXV_M',
    appId: '1:819053432548:ios:27363e1a4c59c04d4a26f1',
    messagingSenderId: '819053432548',
    projectId: 'flutter-instagram-f27bd',
    storageBucket: 'flutter-instagram-f27bd.appspot.com',
    iosClientId: '819053432548-po3dnicfafnrtber41s2db64qoe4d0ci.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.epitech.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PudpcejMzoa9tpBolWxCLDfckkMXV_M',
    appId: '1:819053432548:ios:27363e1a4c59c04d4a26f1',
    messagingSenderId: '819053432548',
    projectId: 'flutter-instagram-f27bd',
    storageBucket: 'flutter-instagram-f27bd.appspot.com',
    iosClientId: '819053432548-po3dnicfafnrtber41s2db64qoe4d0ci.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.epitech.instagram',
  );
}
